apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Default policy for users without specific roles
  policy.default: role:readonly
  
  # RBAC policy configuration
  policy.csv: |
    # Admins have full access
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, logs, *, *, allow
    p, role:admin, exec, *, */*, allow
    
    # Developers can view and sync applications in dev namespace
    p, role:developer, applications, get, dev/*, allow
    p, role:developer, applications, sync, dev/*, allow
    p, role:developer, applications, action/*, dev/*, allow
    p, role:developer, logs, get, dev/*, allow
    
    # QA engineers can view and sync applications in qa namespace
    p, role:qa, applications, get, qa/*, allow
    p, role:qa, applications, sync, qa/*, allow
    p, role:qa, logs, get, qa/*, allow
    
    # Readonly role for viewing all applications
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, logs, get, */*, allow
    
    # Group bindings
    g, admins, role:admin
    g, developers, role:developer
    g, qa-team, role:qa

