apiVersion: v2
name: my-app
description: A sample microservice application for demonstrating GitOps deployment
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - microservice
  - demo
  - gitops

maintainers:
  - name: Platform Team
    email: platform@example.com

annotations:
  category: Application

