apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-app-pdb
  labels:
    app.kubernetes.io/name: my-app
    app.kubernetes.io/part-of: my-app
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
      app.kubernetes.io/instance: my-app

