apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-pdb
  namespace: loki
  labels:
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/component: logging
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
