# ArgoCD Projects 定义
# 通过 root-app GitOps 管理
---
# ArgoCD Project for platform infrastructure
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  description: Platform infrastructure components (LGTM observability stack)
  
  sourceRepos:
    - https://github.com/0xByteLeon/gitops-manifests.git
    - https://grafana.github.io/helm-charts
    - https://prometheus-community.github.io/helm-charts
    - https://open-telemetry.github.io/opentelemetry-helm-charts
  
  # Each platform component has its own namespace
  destinations:
    - namespace: prometheus
      server: "*"
    - namespace: grafana
      server: "*"
    - namespace: loki
      server: "*"
    - namespace: tempo
      server: "*"
    - namespace: opentelemetry
      server: "*"
    - namespace: otel-collector
      server: "*"
  
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
# ArgoCD Project for business applications
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: gitops
spec:
  description: Business applications
  
  sourceRepos:
    - https://github.com/0xByteLeon/gitops-manifests.git
    - https://open-telemetry.github.io/opentelemetry-helm-charts
  
  destinations:
    - namespace: dev
      server: "*"
    - namespace: qa
      server: "*"
    - namespace: prod
      server: "*"
    - namespace: otel-demo
      server: "*"
    - namespace: my-app
      server: "*"
  
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
